<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxfaa0e\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxfaa0e/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFxfaa0e.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFxfaa0e\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerFxfaa0e\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'Fxfaa0e',
    'container.build_id' => '1d07adfd',
    'container.build_time' => 1680629340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxfaa0e');
